### ISSUE TITLE
Create new nickel patch to customise style of new header/footer

### ISSUE THREAD

**Issue by jackiew1** [geek1011/kobopatch-patches#26]
GeoffR's old patch "Custom reading footer style" included customisation of both height and style of the old footer.

The new patch "Reduce new header/footer height" handles the height part for both header/footer. There is not yet a patch to handle the style aspects. I am working on adding it.

It will be of most use to users where the default Avenir font serves their native language quite badly because it is not a Kobo-supported language, e.g. Russian, Vietnamese. However it will be usable by anyone for purely cosmetic purposes or just-because-we-like-to-tinker.

**Comment by NiLuJe** [comment]
Random remark: choosing a font with poor Unicode coverage as a font used to display chapter/book titles seem like a weird choice, given the fact that even English language books might contain non-Latin titles...

**Comment by jackiew1** [comment]
Can't argue with that. The old method of using the user-selected font for both book content and header/footer was better.

Personally I prefer sans-serif for all GUI stuff (serif for book content), but at least provide a half-decent sans-serif. Perhaps it's too expensive. The CJK fallback for Avenir is horrendous for Cyrillic - every char double-spaced.

**Comment by geek1011** [comment]
And, here's a patch to prevent uppercasing the header/footer:

```yaml
Make book header/footer lowercase:
  - Enabled: no
  - PatchGroup: Header/footer page number text
  # In ReadingView::getChapterTitle (header), NOP QString::toUpper call:
  - ReplaceBytesNOP: {Offset: 0xA366EC, FindBLX: 0x440474}
  # In ReadingView::updateFooter, NOP QString::toUpper call:
  - ReplaceBytesNOP: {Offset: 0xA39C36, FindBLX: 0x440474}
  # Page number text
  - FindReplaceString: {Find: "%1 OF %2", Replace: "%1 of %2"}
```
