### ISSUE TITLE
Kobo Forma's orientation is momentarily upside down after every wake or power-on

### ISSUE THREAD

**Issue by hub2git** [geek1011/kobopatch-patches#33]
I like holding my Kobo Forma in my right hand.
On my Kobo Forma, I have inverted "Next" and "Previous" page-control hardware buttons. 

These two things combined seem to cause my Forma, after waking up or powering on, to momentarily have the text or the enter-your-PIN page to be upside down, before correcting itself to be right-side up. I don't want to waste time every time I pick up my Forma waiting for it to have the right orientation.  That wastes 5 seconds every time.

I noticed that when my Next and Previous buttons are not inverted, I don't have this temporary hiccup. But, I will not choose "non-inverted" just to avoid this hiccup. I would like to invert my page-control buttons AND not have this glitch.

geek1011, can you add a patch that fixes this?
Maybe we can we can force the Kobo Forma into one of five orientations (regardless of Kobo's pitch axis):
1. handle on the right (for me, since I like to hold the Kobo with my right hand)
2. handle on the left
3. handle at the bottom (landscape)
4. handle at the top (bats, circus performers, and handstand-walkers would appreciate this orientation)
5. Automatic (based on pitch-axis sensor)

**Comment by geek1011** [comment]
The orientation stuff won't be worth the effort to patch, but I can easily make a workaround which inverts the page buttons without having that option selected. Would that be sufficient for your needs?

**Comment by geek1011** [comment]
You can use this libnickel patch on 4.18.13737 to invert the page buttons without affecting anything else:

```yaml
Invert page turn buttons:
  - Enabled: yes
  # In ReadingView::keyPressEvent(QKeyEvent*), invert the branch to next page:
  - ReplaceBytes: {Offset: 0xAD2824, FindH: 28 B9, ReplaceH: 28 B1} # CBNZ R0, #0xE -> CBZ R0, #0xE
```

If this is not sufficient for working around your issue, you'll need to wait until Kobo fixes it or I come across a simple way to fix it.
