### ISSUE TITLE
Change Google search language

### ISSUE THREAD

**Issue by geek1011** [geek1011/kobopatch-patches#43]
MR:post-3927495, MR:post-3925934.

**Comment by geek1011** [comment]
4.19.14123 (MR:post-3928212):

```yaml
Change Google search language:
  - Enabled: no
  - Description: Changes the language used for Google in the reader selection menu.
  # In WebSearchMixinBase::doGoogleSearch:
  # don't let the firmware override the hl parameter (NOP QUrlQuery::addQueryItem)
  - ReplaceBytesNOP: {Offset: 0x86EBAE, FindBLX: 0x4CE0B0}
  # hl = interface language
  # gl = primary search result country
  # See https://developers.google.com/custom-search/docs/xml_results_appendices#interfaceLanguages
  - FindReplaceString: {Find: "https://www.google.com/search?safe=active", Replace: "https://google.com/search?hl=en&gl=en"}
```
