### ISSUE TITLE
Patches for 4.20.14601

### ISSUE THREAD

**Issue by geek1011** [geek1011/kobopatch-patches#48]
- [x] Upload testdata (@geek1011)
- [x] Test dictionary stuff (it changed quite a bit) (for dictutil and the dictionary patches) (@geek1011)
- [x] Look for user-facing firmware changes and bugfixes (@geek1011)
- [x] Find libnickel offsets (@geek1011)
- [x] Find libadobe offsets (@geek1011)
- [x] Find librmsdk offsets (@geek1011)
- [x] Update patches (@geek1011)
- [x] Update nickel patches if necessary (@jackiew1)
  - [x] Dictionary stuff
- [x] Rewrite patches if necessary
  - [x] Hide browser (@geek1011)
  - [x] Show all games (@geek1011)
  - [x] KePub stylesheet additions (@geek1011)
  - [x] Hide browser (@geek1011)
  - [x] Remove PDF map widget shown during panning (@geek1011)
  - [x] Remove PDF page turn arrows (not needed anymore) (@geek1011)
  - [x] Keep PDF pan position (won't work anymore?, so I'll just remove it) (@geek1011)
- [x] Test most patches (@geek1011)
- [x] Make release (@geek1011)
- [x] MR post (@geek1011)

**Comment by geek1011** [comment]
- The new selection menu is nice. The selection now appears with a solid black background rather than an underline, and the menu is now more compact, with submenus instead of tabs.
- The new dictionary view is more streamlined, but is still just as small (it does have a fullscreen button, though). I haven't checked the functionality or if this is patchable yet. The extra dictionaries bug still remains, though (the one which requires a patch to fix the space splitting).

**Comment by geek1011** [comment]
- Image tags in dictionaries with `dict:///` URLs don't segfault anymore, but they don't display either.

**Comment by jackiew1** [comment]
@geek1011 
I believe I've got the necessary change for libnickel.so.1.0.0.yaml to make patch `'Dictionary text font-family/font-size/line-height`' work again. However, I haven't had time to apply it to an actual Kobo yet to double-check.

**Comment by geek1011** [comment]
@jackiew1: Thanks for looking into that. I'll make the patch folder for 4.20.14601 soon (I haven't started working on the patches yet, as I was working on dictutil: see [v0.0.1-alpha.4](https://github.com/geek1011/dictutil/releases/tag/v0.0.1-alpha.4)).

**Comment by jackiew1** [comment]
@geek1011 
Re: nickel.yaml patches ... just based on the ones I use myself my initial gut feel is that very little has changed in this fw.

**Comment by geek1011** [comment]
Yep. The main interface changes I've noticed are with the selection menu and dictionary.

I'll need to rewrite the hide browser patch.

**Comment by geek1011** [comment]
@jackiew1: None of your nickel patches are broken. I'm planning to release the patches tonight (I'll start working on them in an hour or so), so if you have the `Dictionary text font-family/font-size/line-height` change ready (you can post it in this issue), I'll include it in the initial release.

It also seems like the adobe libs have been updated in this version, so I'll need to fix those patches too.

**Comment by jackiew1** [comment]
> @jackiew1: None of your nickel patches are broken. I'm planning to release the patches tonight (I'll start working on them in an hour or so), so if you have the `Dictionary text font-family/font-size/line-height` change ready (you can post it in this issue), I'll include it in the initial release.

I don't see any 4.20 yaml files for me to update if you want me to do them tonight.

Did you also notice that the libnickel.so.1.0.0.yaml `KePub stylesheet additions` patch is broken?

**Comment by geek1011** [comment]
> I don't see any 4.20 yaml files for me to update if you want me to do them tonight.
Yes, they're not ready yet. If you post the changes here, I'll commit them for you.

> Did you also notice that the libnickel.so.1.0.0.yaml KePub stylesheet additions patch is broken?
Yes, I noticed that. It should be simple enough to fix.

**Comment by jackiew1** [comment]
> > I don't see any 4.20 yaml files for me to update if you want me to do them tonight.
> 
> Yes, they're not ready yet (I'm starting to work on the patches in a few minutes). If you post the changes here, I'll commit them for you later tonight.

Here are the changes to Find/Replace and the help notes.
```
  # Stage 1: Change DictionaryView to remove %variables
  # from:
  #    * { font: %1px %2; line-height: 1.4em; }
  #    div.descriptionFont { font-family: %3; }
  #    ol { font-size: %1px; font-weight: bold; margin-left: %4em; margin-top: 0px; }
  #    ol p { font-size: %1px; font-weight:normal; }
  # to:
  #    * { font-size: %1px; line-height: 1.40em;font-family: Georgia                       ;}
  #    ol {margin-left:1em; margin-top:0}
  #    blockquote {margin:0.3em 0 0.3em 1em} blockquote>blockquote {margin:-0.3em 0 0 2em}
  #
  # ##### N.B. Do not change the next 4 lines #####
  - FindReplaceString:
      Find:    "* { font: %1px %2; line-height: 1.4em; }\ndiv.descriptionFont { font-family: %3; }\nol { font-size: %1px; font-weight: bold; margin-left: %4em; margin-top: 0px; }\nol p { font-size: %1px; font-weight:normal; }\n"
      Replace: "* { font-size: %1px; line-height: 1.40em;font-family: Georgia                       ;}\n\nol {margin-left:1em; margin-top:0}\nblockquote {margin:0.3em 0 0.3em 1em} blockquote>blockquote {margin:-0.3em 0 0 2em}\n"
      MustMatchLength: yes
  # ##### N.B. Do not change anything above this line #####

```
