### ISSUE TITLE
Series tab CSS patches

### ISSUE THREAD

**Issue by geek1011** [geek1011/kobopatch-patches#52]
MR:post-3960493

**Comment by jackiew1** [comment]
Added beta to MR:post-3960493 for Dragon devices only for now. 

Unfortunately it's difficult to optimise patch to suit all Dragon devices. Maximising ClaraHD cover thumbnails results in 5th (bottom) cover being truncated on H2O. I got around this by adding a second beta patch to reduce the height of the page navigation arrows at the bottom of the Series list page (which also affects other booklist pages).

There's a similar issue/workaround when trying to choose best values for Daylight devices. Maximising for Forma causes truncation on KA1.

The other option would be to make the thumbnails small enough so they don't truncate even when the nav arrows are full height. Kind of counter-productive to the purpose of the patch, though.

Only going to include this in standard pack if there are enough volunteers to test settings for Trilogy, Phoenix, LibraH20. Given issues stated above can't really guess without active co-operation from other users.

**Comment by geek1011** [comment]
@jackiew1, have you decided if you're going to include this yet? I can test it on my Mini (trilogy) and Aura2v1 (phoenix).

**Comment by NiLuJe** [comment]
I can also test on a H2O (which doesn't help :D), and a Forma (which probably does, since it's using the scales of a KA1 with a different screen size).

**Comment by jackiew1** [comment]
@geek1011 
I didn't realise you could cover the Trilogy/Phoenix device testing. I can do the KA1/Forma. That will still leave the LibraH20 missing. I thought following the original request and the Dragon beta I posted that other users might have pushed for the missing devices, but so far they haven't so it can't be urgent.

Ideally I'd like to defer this for another week or two. I'm still really struggling with the tendinitis/RSI. Even the fairly limited work I did on the 4.20 release has made it flare up worse than ever.

**Comment by geek1011** [comment]
OK, sounds good. I'll leave it for v60, then (v59 will be released as soon as I get around to fixing the 24 line spacing values patch).

**Comment by rtiangha** [comment]
To be fair, part of the reason could also be that Series tab support only showed up in Calibre on Friday so maybe people haven't had time to upgrade yet and/or sync to be able to play with the new feature or to notice the difference in size.

But I appreciate the patch. Feel better!!

**Comment by jackiew1** [comment]
@geek1011 @NiLuJe 
I've done some more work on this. I blew the cobwebs off my Glo & Aurav1, so now I think I've tested Glo, Aura6"v1, AuraHD, H2O, ClaraHD, KA1, Forma. Confirmation by second opinion would be helpful from both of you. 😄 

@geek1011 
This is only as urgent as you want it to be. Please will you test on any devices you can get hold of. The `Trilogy` (and LibraH2O) values in the patches below are pure guesswork. This is an outline of the process I used for testing the other models:
- To begin with only enable patch `beta Series list increase cover thumbnails`.
- Set the Part 2 `height` replacement high at first. Reduce it gradually until there is no truncation of the bottom edge of the top 4 thumbnails on each page. The bottom of each thumbnail should be sitting on the horizontal gridline below it. If it's not, the `height` value is too low. (_Finding books in my library where it's obvious when the bottom is truncated was time-consuming for me_).
- At this point the 5th thumbnail may still be truncated, but leave the `height` value alone now.
- Enable the 2nd patch `beta Reduce height of page navigator arrows` which should stop the 5th thumbnail truncating. If it doesn't, reduce the min/max-height values more until the truncation problem goes away.

Patch 1:
```
beta Series list increase cover thumbnails:
  - Enabled: no
  - Description: |
        Series list view (not cover view). Enlarge cover thumbnails.
        NB: After enabling this patch, if you find that the 
            last Series thumbnail on each page is truncated along its bottom edge
            then you should also enable the following nickel patch:
            'Reduce height of page navigator arrows'
  - FindZlib: "#seriesCoverPack"
  - ReplaceZlibGroup:
      Replacements:
        # Part 1: #seriesWidgetContainer - Reduce top/bottom margins
        #   NB: The smaller the topMargin the closer the Series name
        #       will be to the horizontal gridline above it
          # Touch/Mini
        - {Find: "topMargin: 9px;",     Replace: "topMargin: 3px;"}
        - {Find: "bottomMargin: 9px;",  Replace: "bottomMargin: 0px;"}
          # Glo/Aura6"/Aurav2
        - {Find: "topMargin: 12px;",    Replace: "topMargin: 4px;"}
        - {Find: "bottomMargin: 12px;", Replace: "bottomMargin: 0px;"}
          # AuraHD/H2O/H2Ov2/GloHD/ClaraHD
        - {Find: "topMargin: 14px;",    Replace: "topMargin: 5px;"}
        - {Find: "bottomMargin: 14px;", Replace: "bottomMargin: 0px;"}
          # AuraOne/Forma
        - {Find: "topMargin: 21px;",    Replace: "topMargin: 7px;"}
        - {Find: "bottomMargin: 21px;", Replace: "bottomMargin: 0px;"}
          # LibraH2O
        - {Find: "topMargin: 17px;",    Replace: "topMargin: 6px;"}
        - {Find: "bottomMargin: 17px;", Replace: "bottomMargin: 0px;"}
        #
        # Part 2: #seriesCoverPack - Increase cover thumbnail size
          # Touch/Mini (pure guesswork)
        - {Find: "width: 60px;",   Replace: "width: 85px;"}
        - {Find: "height: 94px;",  Replace: "height: 105px;"}
          # Glo/Aura6"/Aurav2
        - {Find: "width: 70px;",   Replace: "width: 100px;"}
        - {Find: "height: 115px;", Replace: "height: 140px;"}
          # AuraHD/H2O/H2Ov2/GloHD/ClaraHD
        - {Find: "width: 108px;",  Replace: "width: 141px;"}
        - {Find: "height: 175px;", Replace: "height: 200px;"}
          # AuraOne/Forma
        - {Find: "width: 140px;",  Replace: "width: 190px;"}
        - {Find: "height: 222px;", Replace: "height: 265px;"}
          # LibraH2O (pure guesswork)
        - {Find: "width: 126px;",  Replace: "width: 165px;"}
        - {Find: "height: 205px;", Replace: "height: 232px;"}
        #
        # Part 3: All models: #hBooks - Move bookcount up & away from horizontal gridline
        #         Users of lower-res models (Touch/Mini/Glo/Aura6"/Aurav2) may prefer to 
        #         decrease the Replace value of 20px for padding-bottom
        - Find:    "#hBooks {\n  padding-left: 0px;\n  padding-bottom: 0px;\n  font-style: normal;\n}"
          Replace: "#hBooks {\n  padding-left: 0px;\n  padding-bottom:20px;\n  font-style: normal;\n}"
```
Patch 2:
```
beta Reduce height of page navigator arrows:
  - Enabled: no
  - Description: |
        Reduce page navigator footer height (Book list, Series list)
        This patch may be helpful to users who also enable the nickel patch
        'Series list increase cover thumbnails'
        It should prevent the white background of the page footer/navigation arrow 
        overlapping the bottom edge of the last Serieslist thumbnail on each page.
  - FindZlib: "QWidget[footerFixedHeight=true][qApp_deviceIsTrilogy=true]"
  - ReplaceZlibGroup:
      Replacements:
          # Touch/Mini (pure guesswork)
        - Find:    "QWidget[footerFixedHeight=true][qApp_deviceIsTrilogy=true] {\n  min-height: 70px;\n  max-height: 70px;\n}"
          Replace: "QWidget[footerFixedHeight=true][qApp_deviceIsTrilogy=true] {\n  min-height: 54px;\n  max-height: 54px;\n}"
          # Glo/Aura6"/Aurav2
        - Find:    "QWidget[footerFixedHeight=true][qApp_deviceIsPhoenix=true] {\n  min-height: 82px;\n  max-height: 82px;\n}"
          Replace: "QWidget[footerFixedHeight=true][qApp_deviceIsPhoenix=true] {\n  min-height: 70px;\n  max-height: 70px;\n}"
          # AuraHD/H20/H20v2/GloHD/ClaraHD
        - Find:    "QWidget[footerFixedHeight=true][qApp_deviceIsDragon=true] {\n  min-height: 120px;\n  max-height: 120px;\n}"
          Replace: "QWidget[footerFixedHeight=true][qApp_deviceIsDragon=true] {\n  min-height: 90px;\n  max-height: 90px;\n}"
          # AuraOne/Forma
        - Find:    "QWidget[footerFixedHeight=true][qApp_deviceIsDaylight=true] {\n  min-height: 156px;\n  max-height: 156px;\n}"
          Replace: "QWidget[footerFixedHeight=true][qApp_deviceIsDaylight=true] {\n  min-height: 120px;\n  max-height: 120px;\n}"
          # LibraH2O (pure guesswork)
        - Find:    "QWidget[footerFixedHeight=true][qApp_deviceIsStorm=true] {\n  min-height: 138px;\n  max-height: 138px;\n}"
          Replace: "QWidget[footerFixedHeight=true][qApp_deviceIsStorm=true] {\n  min-height: 105px;\n  max-height: 105px;\n}"
```
