### ISSUE TITLE
Footnote patches in 4.20.xx

### ISSUE THREAD

**Issue by jackiew1** [geek1011/kobopatch-patches#55]
@geek1011 

I don't think your official nickel patch `Change pop-up footnote font-family` is doing anything anymore. If the aim is to make sure pop-up footnotes use Georgia (rather than Avenir) then I think the patch can be removed. However, if the aim is to give font-family full customisation to the user then I think a new pop-up footnote code investigation is needed. Second opinions welcome 😄 

As a follow on ... I've previously posted an unofficial patch to control font-size of footnote text. This no longer works either. As with many parts of the GUI (IMO) default footnote font-size on a KA1/Forma is huge. Other models seem OK. 
```
test Pop-up footnote main text font-size:
  - Enabled: no
  - Description: Change font-size of pop-up footnote main text.
  - FindZlib: "RegularTouchLabel {\n  font-family"
  - ReplaceZlibGroup:
      Replacements:
        # RegularTouchLabel Popup footnote main text
        # Change Replace font-size as required for your Kobo model
          #Touch/Mini
        - Find:    "RegularTouchLabel[qApp_deviceIsTrilogy=true] {\n  font-size: 19px;\n}"
          Replace: "RegularTouchLabel[qApp_deviceIsTrilogy=true] {\n  font-size: 19px;\n}"
          #Glo/Aura/Aura2
        - Find:    "RegularTouchLabel[qApp_deviceIsPhoenix=true] {\n  font-size: 23px;\n}"
          Replace: "RegularTouchLabel[qApp_deviceIsPhoenix=true] {\n  font-size: 23px;\n}"
          #AuraHD/H2O/H2O2
        - Find:    "RegularTouchLabel[qApp_deviceIsDragon=true] {\n  font-size: 29px;\n}"
          Replace: "RegularTouchLabel[qApp_deviceIsDragon=true] {\n  font-size: 29px;\n}"
          #GloHD
        - Find:    "RegularTouchLabel[qApp_deviceIsAlyssum=true] {\n  font-size: 32px;\n}"
          Replace: "RegularTouchLabel[qApp_deviceIsAlyssum=true] {\n  font-size: 32px;\n}"
          #ClaraHD
        - Find:    "RegularTouchLabel[qApp_deviceIsNova=true] {\n  font-size: 32px;\n}"
          Replace: "RegularTouchLabel[qApp_deviceIsNova=true] {\n  font-size: 32px;\n}"
          #LibraH2O
        - Find:    "RegularTouchLabel[qApp_deviceIsStorm=true] {\n  font-size: 34px;\n}"
          Replace: "RegularTouchLabel[qApp_deviceIsStorm=true] {\n  font-size: 34px;\n}"
          #AuraOne/Forma
        - Find:    "RegularTouchLabel[qApp_deviceIsDaylight=true] {\n  font-size: 37px;\n}"
          Replace: "RegularTouchLabel[qApp_deviceIsDaylight=true] {\n  font-size: 34px;\n}"
```

The only workaround I've found so far is a new libnickel patch, but it's not ideal because it doesn't allow a different font-size per model.
```
test Pop-up footnote main text font-size:
  - Enabled: no
  - Description: |
        Change pop-up footnote main text font-size
        fw 4.20.14601 CSS moved to libnickel.so.1.0.0 from nickel???
        Daylight: %1 = 42 ???
  - FindReplaceString:
      Find:    "p { font-size: %1px; line-height: 1.4em; }"
      Replace: "p { font-size: 34px; line-height: 1.4em; }"
      MustMatchLength: yes
```

If we knew where the `%1px` value was being read from it might be a help.
